spring.application.name=lostfound

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
app.jwt.secret=${JWT_SECRET:MySuperSecretKeyForAnonymousQRFinderProjectWhichMustBeAtLeast32BytesLong}

# Server
server.port=${SERVER_PORT:8080}
